# ---
# clusterName: "elasticsearch"
# nodeGroup: "master"

# secret:
#   password: password

# fullNameOverride: els
# nameOverride: els

# replicas: 2
# minimumMasterNodes: 2

# readinessProbe:
#   failureThreshold: 10

# antiAffinity: ""

# createCert: false

security:
  # -- Enable security
  enabled: true
  # -- Default username
  name: elastic
  # -- Default password
  password: password