apiVersion: apps/v1
kind: Deployment
metadata:
    name: app-back
    labels:
        app: app-back
spec:
    replicas: 1
    selector:
        matchLabels:
            app: back
    template:
        metadata:
            labels:
                app: back
        spec:
          initContainers:
            - name: migrations
              image: ghcr.io/impsdc/kubi-back:latest
              imagePullPolicy: Always
              command:
                  - php
              args:
                  - artisan
                  - migrate
                  - --force
              envFrom:
                - configMapRef:
                    name: back-configmap
                - secretRef:
                    name: back-secret
                - secretRef: 
                    name: mysql-secret 
          containers:
            - name:  back
              image: ghcr.io/impsdc/kubi-back:latest
              imagePullPolicy: Always
              ports:
              - containerPort: 80
              envFrom:
                - configMapRef:
                    name: back-configmap
                - secretRef:
                    name: back-secret
                - secretRef: 
                    name: mysql-secret 
          imagePullSecrets:
          - name: ghcr-credentials
            
---
apiVersion: v1
kind: Service
metadata:
  name: back-service
spec:
  selector:
    app: back
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP

