apiVersion: v1
kind: ConfigMap
metadata:
    name: back-configmap
data:
    env-file: |
        APP_NAME=Laravel
        APP_ENV=system
        APP_KEY=base64:h55oToUypq1BJwhcBAbtCnKscJGGS7xXF3zoDNf/yWE=
        APP_DEBUG=true
        APP_URL=http://kubi.com

        LOG_CHANNEL=stderr
        
        BROADCAST_DRIVER=log
        CACHE_DRIVER=file
        QUEUE_CONNECTION=sync
        SESSION_DRIVER=file
        SESSION_LIFETIME=120

        ELASTICSEARCH_HOST=els
        ELASTICSEARCH_PORT=9200
        ELASTICSEARCH_SCHEME=http
        ELASTICSEARCH_USER=elastic
        ELASTICSEARCH_PASS=password
        
---

apiVersion: v1
kind: Secret
metadata:
    name: back-secret
type: Opaque
data:
    DB_CONNECTION: bXlzcWw=
    DB_PORT: MzMwNg==
    DB_HOST: bXlzcWwtc2VydmljZQ==
    DB_USERNAME: cm9vdA==
    
