services:
  db:
    container_name: db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'

  back: 
    container_name: back
    build:
      context: ./back
      dockerfile: Dockerfile
    tty: true
    command: /bin/bash -c "php artisan migrate:refresh && service nginx start && php-fpm"
    ports:
      - 8080:80
    networks:
      - elastic

    depends_on:
      - db
      - elasticsearch
      - amqp

  front:
    container_name: front
    build:
      context: ./front
      dockerfile: Dockerfile
    tty: true
    ports:
      - 8000:80
    restart: always

  amqp:
    container_name: rabbitmq
    image: rabbitmq:management
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - 5672:5672
      - 15672:15672

  indexer:
    container_name: indexer
    build:
      context: ./indexer
      dockerfile: Dockerfile
    tty: true
    ports:
      - 5000:80
    networks:
      - elastic

    depends_on:
      - elasticsearch
      - amqp

  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - MAX_LOCKED_MEMORY=unlimited
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - discovery.zen.minimum_master_nodes=2
      - ELASTIC_USER=user
      - ELASTIC_PASSWORD=password
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 1000M
    ports:
      - 9200:9200

networks:
  elastic:
    name: elastic
    driver: bridge